export const pleiQuotes = [
  'Não esqueça de fazer o acoxambro.',
  'Faz um objeto para gerar um objeto de objetos.',
  'E dentro desses objetos engravidamos os safados com um objeto genérico.',
  'E ai meu rei, vamo tá glorioso.',
  'A parada vai ficar sinistra com esse vagabundo bizarro que vai descaralhar a porra toda.',
  'Fiz um acoxambro em php que ficou glorioso.',
  'Fazer um framework node pra vagabundo bater.',
  'Vamo dar carinho pro cliente.',
  'Vamu engravidá o vagabundo.',
  'Vai ser glorioso.',
  'Pega o vagabundo.',
  'Vagabundo fabuloso descaralha a porra toda.',
  'Cria uma API de objeto de objeto.',
  'Vai gerar um objeto de objeto.',
  'Da um plei no coiso.',
  'Engravida o safado com o coiso.',
  'Faz uma função que da um get no coiso.',
  'Retorna o vagabundo.',
];
